name: Infracost Cost Estimation

on:
  workflow_dispatch:
    inputs:
      port_context:
        required: true
        description: >-
          Port's payload, including details for who triggered the action and
          general context (blueprint, run id, etc...)

jobs:
  infracost:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install Infracost
      - name: Install Infracost
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          echo "$HOME/.infracost/bin" >> $GITHUB_PATH

      # Step 3: Configure Infracost API key
      - name: Configure Infracost API key
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        run: infracost configure set api_key $INFRACOST_API_KEY

      # Step 4: Run Infracost Breakdown in JSON format
      - name: Run Infracost Breakdown
        id: infracost_output
        run: infracost breakdown --path . --format json > infracost_result.json

      # Step 5: Capture Total Cost from JSON Output
      - name: Extract Total Cost from Infracost Result
        id: extract_cost
        run: |
          total_cost=$(jq -r '.projects[].breakdown.totalMonthlyCost' infracost_result.json)
          echo "TOTAL_COST=$total_cost" >> $GITHUB_ENV

  Update_Run:
    needs: infracost
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (needed if accessing other files)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Debugging - Print GitHub Event Payload
      - name: Debug GitHub Event Payload
        run: echo "Port Payload: ${{ toJson(github.event.inputs) }}"

      # Step 3: Inform cost of new environment
      - name: Inform cost of new environment
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: PATCH_RUN
          runId: ${{ fromJson(github.event.inputs.port_payload).context.runId }}
          logMessage: "Total Monthly Cost Estimate: ${{ env.TOTAL_COST }}"