name: Infracost Cost Estimation

on:
  push:
    branches:
      - main

jobs:
  infracost:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install Infracost
      - name: Install Infracost
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
          echo "$HOME/.infracost/bin" >> $GITHUB_PATH

      # Step 3: Configure Infracost API key
      - name: Configure Infracost API key
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        run: infracost configure set api_key $INFRACOST_API_KEY

      # Step 4: Authenticate Infracost
      - name: Infracost Authenticate
        run: infracost auth login

      # Step 5: Run Infracost Breakdown on the Terraform files
      - name: Run Infracost Breakdown
        run: infracost breakdown --path .
